{% set python_min = '3.10' %}
{% set name = "radarx" %}
{% set version = "0.2.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 5d3af120369c41b3acbb773b294609065f45449da65d9c78fcad4cb4791de548

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
    - setuptools_scm

  run:
    - python >={{ python_min }}
    - packaging
    - numpy
    - netcdf4
    - xarray >=2024.10.0
    - xmltodict
    - pyproj
    - cartopy >=0.20.0
    - boto3
    - pooch
    - xradar

test:
  imports:
    - radarx
  requires:
    - pip
    - python {{ python_min }}
  commands:
    - pip check

about:
  home: https://github.com/syedhamidali/radarx
  summary: 'Xarray-based radar toolkit for radar data analysis'
  description: |
    radarx is a Python package built for processing and visualizing radar data using xarray, integrating closely with xradar and datatree libraries for effective manipulation of radar data.
  license: MIT
  license_family: MIT
  license_file: LICENSE
  dev_url: https://github.com/syedhamidali/radarx
  doc_url: https://radarx.readthedocs.io/

extra:
  recipe-maintainers:
    - syedhamidali
