{% set name = "radarx" %}
{% set version = "0.2.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 5c9e0eb3e4328548f5f86d5fd623febed64c76f12c6490bd9520a0f719ef3dd8

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.10
    - pip
    - setuptools
    - setuptools_scm

  run:
    - python >=3.10
    - packaging
    - numpy
    - netcdf4
    - xarray >=2024.10.0
    - xmltodict
    - pyproj
    - cartopy >=0.20.0
    - boto3
    - pooch
    - xradar

test:
  imports:
    - radarx
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/syedhamidali/radarx
  summary: 'Xarray-based radar toolkit for radar data analysis'
  description: |
    radarx is a Python package built for processing and visualizing radar data using xarray, integrating closely with xradar and datatree libraries for effective manipulation of radar data.
  license: MIT
  license_family: MIT
  license_file: LICENSE
  dev_url: https://github.com/syedhamidali/radarx
  doc_url: https://radarx.readthedocs.io/

extra:
  recipe-maintainers:
    - syedhamidali